# Generated by Django 5.2.1 on 2025-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_articlegroupobjectpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='文章被访问的次数', verbose_name='访问次数'),
        ),
    ]
