# Generated by Django 5.2.1 on 2025-06-20 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_add_view_count_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at'], name='articles_ar_created_312397_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-created_at'], name='articles_ar_status_1c9ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status'], name='articles_ar_author__8254d9_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-view_count'], name='articles_ar_view_co_f1b57c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='articles_ar_title_ee81af_idx'),
        ),
    ]
