# Generated by Django 5.2.1 on 2025-06-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                help_text="用于邮箱验证的token",
                max_length=64,
                verbose_name="邮箱验证token",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="用户激活状态"),
        ),
    ]
