# Generated by Django 5.2.1 on 2025-06-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_update_avatar_upload_path'),
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
    ]
