# Generated by Django 5.2.1 on 2025-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250618_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='用户最后一次登录的IP地址', null=True, verbose_name='最后登录IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.PositiveIntegerField(default=0, help_text='用户总登录次数', verbose_name='登录次数'),
        ),
    ]
