# Generated by Django 5.2.1 on 2025-06-19 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comments', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['parent_id', 'created_at'], 'permissions': [('moderate_comment', '可以审核评论'), ('reply_comment', '可以回复评论'), ('manage_comment', '可以管理评论')], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.CreateModel(
            name='CommentGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment', verbose_name='评论')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'verbose_name': '评论组权限',
                'verbose_name_plural': '评论组权限',
            },
        ),
        migrations.CreateModel(
            name='CommentUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment', verbose_name='评论')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论用户权限',
                'verbose_name_plural': '评论用户权限',
            },
        ),
    ]
